apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config-company
data:
  init.sql: |
    ALTER USER postgres PASSWORD 'password';
    CREATE TABLE companies
    (
        id          SERIAL PRIMARY KEY,
        name        VARCHAR(255)   NOT NULL,
        website     VARCHAR(255)   NOT NULL,
        email       VARCHAR(255)   NOT NULL,
        phone       INTEGER        NOT NULL,
        created_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        updated_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        UNIQUE (name)
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
    spec:
      containers:
        - name: company-service
          image: nicolajh/swj-company
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: databasesecrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databasesecrets
                  key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: databasesecrets
                  key: connection-string-company-service
            - name: POSTGRES_DB
              value: database-company-service
            - name: POSTGRES_HOST
              value: postgres
            - name: URL_JOBSERVICE
              value: http://job-service:8080/api/jobs
            - name: URL_AUTHENTICATIONSERVICE
              value: http://authentication-service:3000
          resources:
            limits:  
              cpu: "250m"
              memory: "500Mi"
            requests:  
              cpu: "250m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
spec:
  selector:
    app: company-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
